### ISSUE TITLE
Feature Request - directions_option = "none"

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/odin#171]
Allow an option that does not return guidance/narrative directions. Only return locations, shape, and route overview (time, distance).

**Comment by kevinkreiser** [comment]
so would this be something like you leave off `"directions_options":{}` from the request entirely or you pass in something like: `"directions_options":{"narrative":false}` ?

**Comment by dgearhart** [comment]
should maneuvers be created?

**Comment by dnesbitt61** [comment]
I would say no. The main request was for generating the route plots for routes from one location to a whole bunch of others. Here all that is needed is the shape (and may be nice to have total time/distance).

**Comment by kevinkreiser** [comment]
should this be an enhancement to thor then? i mean there is basically nothing else to do after you have a `TripPath` or multiple of them. Should thor just serialize and return the response in this case? In other words, tyr serializes `TripDirections` and since odin isnt doing any work in this case does it even need to go through odin?

**Comment by dnesbitt61** [comment]
if that works this is fine - still think it should be something like narrative false in the directions options like you mentioned

**Comment by dgearhart** [comment]
it just depends if we want odin to create the TripDirections object to keep the flow the same or add in extra logic for tyr - it is an easy update for odin
