### ISSUE TITLE
Odin supports only Germanic-style two-form plural

### ISSUE THREAD

**Issue by mormegil-cz** [valhalla/odin#291]
Messages like `transit_stop_count_labels` used in “_(&lt;TRANSIT_STOP_COUNT&gt; &lt;TRANSIT_STOP_COUNT_LABEL&gt;)_” support only two-form singular/plural distinction, working for English and German, but not for a whole lot of other languages (cf. [a useful overview in Gettext manual](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html)).

Odin should ideally support [CLDR plural rules](http://cldr.unicode.org/index/cldr-spec/plural-rules), e.g.
`"transit_stop_count_labels": {"one": "stop", "other": "stops"}`
for English, while
`"transit_stop_count_labels": {"one": "zastávka", "few": "zastávky", "other": "zastávek"}`
for Czech. Or it could use any existing i18n library supporting similar locale data.

**Comment by kevinkreiser** [comment]
this is great! we were really hoping people would poke holes in our format so that we could find where it didn't support a particular feature of a particular language. we'll try to get something in there to address this. if there are any more things you can think of to improve support for Slavic languages please add more issues!
